//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McKnight.Similization.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class McKnight_Similization_Core {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal McKnight_Similization_Core() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("McKnight.Similization.Core.McKnight.Similization.Core", typeof(McKnight_Similization_Core).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine city happiness based on current state..
        /// </summary>
        internal static string CannotDetermineHappiness {
            get {
                return ResourceManager.GetString("CannotDetermineHappiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cell is not currently being worked by this country..
        /// </summary>
        internal static string CellIsNotBeingWorked {
            get {
                return ResourceManager.GetString("CellIsNotBeingWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command is not enabled.  Set Enabled to true before calling Invoke() on this command..
        /// </summary>
        internal static string CommandDisabled {
            get {
                return ResourceManager.GetString("CommandDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This improvement is not able to be built at this time..
        /// </summary>
        internal static string ImprovementNotAvailable {
            get {
                return ResourceManager.GetString("ImprovementNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Worker Efficiency..
        /// </summary>
        internal static string UnknownWorkerEfficiency {
            get {
                return ResourceManager.GetString("UnknownWorkerEfficiency", resourceCulture);
            }
        }
    }
}
