//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McKnight.SimilizationRulesEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("McKnight.SimilizationRulesEditor.EditorResources", typeof(EditorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air.
        /// </summary>
        internal static string AirUnitType {
            get {
                return ResourceManager.GetString("AirUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this terrain tile?.
        /// </summary>
        internal static string ConfirmTerrainTileDelete {
            get {
                return ResourceManager.GetString("ConfirmTerrainTileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land.
        /// </summary>
        internal static string LandUnitType {
            get {
                return ResourceManager.GetString("LandUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Ruleset.
        /// </summary>
        internal static string OpenRuleset {
            get {
                return ResourceManager.GetString("OpenRuleset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        internal static string ResourceRulesetItem {
            get {
                return ResourceManager.GetString("ResourceRulesetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruleset.
        /// </summary>
        internal static string Ruleset {
            get {
                return ResourceManager.GetString("Ruleset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea.
        /// </summary>
        internal static string SeaUnitType {
            get {
                return ResourceManager.GetString("SeaUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrains.
        /// </summary>
        internal static string TerrainRulesetItem {
            get {
                return ResourceManager.GetString("TerrainRulesetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain Tiles.
        /// </summary>
        internal static string TerrainTileTilesetItem {
            get {
                return ResourceManager.GetString("TerrainTileTilesetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tileset.
        /// </summary>
        internal static string Tileset {
            get {
                return ResourceManager.GetString("Tileset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string UnitRulesetItem {
            get {
                return ResourceManager.GetString("UnitRulesetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Tiles.
        /// </summary>
        internal static string UnitTileTilesetItem {
            get {
                return ResourceManager.GetString("UnitTileTilesetItem", resourceCulture);
            }
        }
    }
}
