//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LJM.Similization.Client.DirectX {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DirectXClientResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DirectXClientResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LJM.Similization.Client.DirectX.DirectXClientResources", typeof(DirectXClientResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Billion.
        /// </summary>
        internal static string Age3Billion {
            get {
                return ResourceManager.GetString("Age3Billion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Billion.
        /// </summary>
        internal static string Age4Billion {
            get {
                return ResourceManager.GetString("Age4Billion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Billion.
        /// </summary>
        internal static string Age5Billion {
            get {
                return ResourceManager.GetString("Age5Billion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age:.
        /// </summary>
        internal static string AgeLabel {
            get {
                return ResourceManager.GetString("AgeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbarians:.
        /// </summary>
        internal static string BarbarianLabel {
            get {
                return ResourceManager.GetString("BarbarianLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raging.
        /// </summary>
        internal static string BarbarianRaging {
            get {
                return ResourceManager.GetString("BarbarianRaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        internal static string BarbarianRandom {
            get {
                return ResourceManager.GetString("BarbarianRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restless.
        /// </summary>
        internal static string BarbarianRestless {
            get {
                return ResourceManager.GetString("BarbarianRestless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roaming.
        /// </summary>
        internal static string BarbarianRoaming {
            get {
                return ResourceManager.GetString("BarbarianRoaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sedentary.
        /// </summary>
        internal static string BarbarianSedentary {
            get {
                return ResourceManager.GetString("BarbarianSedentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilization:.
        /// </summary>
        internal static string CivilizationLabel {
            get {
                return ResourceManager.GetString("CivilizationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arid.
        /// </summary>
        internal static string ClimateArid {
            get {
                return ResourceManager.GetString("ClimateArid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate:.
        /// </summary>
        internal static string ClimateLabel {
            get {
                return ResourceManager.GetString("ClimateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string ClimateNormal {
            get {
                return ResourceManager.GetString("ClimateNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wet.
        /// </summary>
        internal static string ClimateWet {
            get {
                return ResourceManager.GetString("ClimateWet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chieftain.
        /// </summary>
        internal static string DifficultyChieftain {
            get {
                return ResourceManager.GetString("DifficultyChieftain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deity.
        /// </summary>
        internal static string DifficultyDeity {
            get {
                return ResourceManager.GetString("DifficultyDeity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emperor.
        /// </summary>
        internal static string DifficultyEmperor {
            get {
                return ResourceManager.GetString("DifficultyEmperor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King.
        /// </summary>
        internal static string DifficultyKing {
            get {
                return ResourceManager.GetString("DifficultyKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty:.
        /// </summary>
        internal static string DifficultyLabel {
            get {
                return ResourceManager.GetString("DifficultyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prince.
        /// </summary>
        internal static string DifficultyPrince {
            get {
                return ResourceManager.GetString("DifficultyPrince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warlord.
        /// </summary>
        internal static string DifficultyWarlord {
            get {
                return ResourceManager.GetString("DifficultyWarlord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similization.NET.
        /// </summary>
        internal static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archipelago.
        /// </summary>
        internal static string LandMassArchipelago {
            get {
                return ResourceManager.GetString("LandMassArchipelago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continents.
        /// </summary>
        internal static string LandMassContinents {
            get {
                return ResourceManager.GetString("LandMassContinents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land Mass:.
        /// </summary>
        internal static string LandMassLabel {
            get {
                return ResourceManager.GetString("LandMassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pangaea.
        /// </summary>
        internal static string LandMassPangaea {
            get {
                return ResourceManager.GetString("LandMassPangaea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader Name:.
        /// </summary>
        internal static string LeaderNameLabel {
            get {
                return ResourceManager.GetString("LeaderNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a game to load:.
        /// </summary>
        internal static string LoadGameLabel {
            get {
                return ResourceManager.GetString("LoadGameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a Saved Game.
        /// </summary>
        internal static string LoadGameTitle {
            get {
                return ResourceManager.GetString("LoadGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Game.
        /// </summary>
        internal static string MainMenuExitGame {
            get {
                return ResourceManager.GetString("MainMenuExitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Game.
        /// </summary>
        internal static string MainMenuLoadGame {
            get {
                return ResourceManager.GetString("MainMenuLoadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        internal static string MainMenuNewGame {
            get {
                return ResourceManager.GetString("MainMenuNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string MainMenuOptions {
            get {
                return ResourceManager.GetString("MainMenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Start.
        /// </summary>
        internal static string MainMenuQuickStart {
            get {
                return ResourceManager.GetString("MainMenuQuickStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        internal static string MainMenuTutorial {
            get {
                return ResourceManager.GetString("MainMenuTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help....
        /// </summary>
        internal static string MenuItemHelp {
            get {
                return ResourceManager.GetString("MenuItemHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Save.
        /// </summary>
        internal static string MenuItemQuickSave {
            get {
                return ResourceManager.GetString("MenuItemQuickSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit To Desktop.
        /// </summary>
        internal static string MenuItemQuitToDesktop {
            get {
                return ResourceManager.GetString("MenuItemQuitToDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Game....
        /// </summary>
        internal static string MenuItemSaveGame {
            get {
                return ResourceManager.GetString("MenuItemSaveGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similization cannot find a graphics mode suitable for running the program..
        /// </summary>
        internal static string NoModeAvailable {
            get {
                return ResourceManager.GetString("NoModeAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponents.
        /// </summary>
        internal static string OpponentsLabel {
            get {
                return ResourceManager.GetString("OpponentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similization Options.
        /// </summary>
        internal static string OptionsTitle {
            get {
                return ResourceManager.GetString("OptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Setup.
        /// </summary>
        internal static string PlayerSetupTitle {
            get {
                return ResourceManager.GetString("PlayerSetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Civilization Abilities.
        /// </summary>
        internal static string RuleCivilizationAbilities {
            get {
                return ResourceManager.GetString("RuleCivilizationAbilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Cultural Victory.
        /// </summary>
        internal static string RuleCulturalVictory {
            get {
                return ResourceManager.GetString("RuleCulturalVictory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Diplomatic Victory.
        /// </summary>
        internal static string RuleDiplomaticVictory {
            get {
                return ResourceManager.GetString("RuleDiplomaticVictory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Domination Victory.
        /// </summary>
        internal static string RuleDominationVictory {
            get {
                return ResourceManager.GetString("RuleDominationVictory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Military Victory.
        /// </summary>
        internal static string RuleMilitaryVictory {
            get {
                return ResourceManager.GetString("RuleMilitaryVictory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruleset:.
        /// </summary>
        internal static string RulesetLabel {
            get {
                return ResourceManager.GetString("RulesetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        internal static string RulesLabel {
            get {
                return ResourceManager.GetString("RulesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Space Victory.
        /// </summary>
        internal static string RuleSpaceVictory {
            get {
                return ResourceManager.GetString("RuleSpaceVictory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Rules.
        /// </summary>
        internal static string RuleStandard {
            get {
                return ResourceManager.GetString("RuleStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartButtonText {
            get {
                return ResourceManager.GetString("StartButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool.
        /// </summary>
        internal static string TemperatureCool {
            get {
                return ResourceManager.GetString("TemperatureCool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature:.
        /// </summary>
        internal static string TemperatureLabel {
            get {
                return ResourceManager.GetString("TemperatureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperate.
        /// </summary>
        internal static string TemperatureTemperate {
            get {
                return ResourceManager.GetString("TemperatureTemperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm.
        /// </summary>
        internal static string TemperatureWarm {
            get {
                return ResourceManager.GetString("TemperatureWarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tileset:.
        /// </summary>
        internal static string TilesetLabel {
            get {
                return ResourceManager.GetString("TilesetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eighty Percent.
        /// </summary>
        internal static string WaterCoverageEightyPercent {
            get {
                return ResourceManager.GetString("WaterCoverageEightyPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Coverage:.
        /// </summary>
        internal static string WaterCoverageLabel {
            get {
                return ResourceManager.GetString("WaterCoverageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seventy Percent.
        /// </summary>
        internal static string WaterCoverageSeventyPercent {
            get {
                return ResourceManager.GetString("WaterCoverageSeventyPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sixty Percent.
        /// </summary>
        internal static string WaterCoverageSixtyPercent {
            get {
                return ResourceManager.GetString("WaterCoverageSixtyPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your World.
        /// </summary>
        internal static string WorldSetupTitle {
            get {
                return ResourceManager.GetString("WorldSetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huge.
        /// </summary>
        internal static string WorldSizeHuge {
            get {
                return ResourceManager.GetString("WorldSizeHuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Size:.
        /// </summary>
        internal static string WorldSizeLabel {
            get {
                return ResourceManager.GetString("WorldSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        internal static string WorldSizeLarge {
            get {
                return ResourceManager.GetString("WorldSizeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string WorldSizeSmall {
            get {
                return ResourceManager.GetString("WorldSizeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string WorldSizeStandard {
            get {
                return ResourceManager.GetString("WorldSizeStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiny.
        /// </summary>
        internal static string WorldSizeTiny {
            get {
                return ResourceManager.GetString("WorldSizeTiny", resourceCulture);
            }
        }
    }
}
